<a href="https://colab.research.google.com/github/Rekaa-DA/Technology-Company-Analysis-Automation/blob/main/GitHub_API_Data_Collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sample GitHub_API_Data_Collection**

In [ ]:
import requests

In [ ]:
url = "https://api.github.com/orgs/microsoft/repos"

In [ ]:
url = "https://api.github.com/orgs/microsoft/repos"

In [ ]:
response = requests.get(url)

In [ ]:
response.status_code

200

In [ ]:
response.json()

[{'id': 1932083,
  'node_id': 'MDEwOlJlcG9zaXRvcnkxOTMyMDgz',
  'name': 'HealthVault-Mobile-iOS-Library',
  'full_name': 'microsoft/HealthVault-Mobile-iOS-Library',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
  'description': "The HealthVault team has recently added the capability to write applications that will run on Mobile Devices and connect directly to the HealthVault Service. HealthVault iOS library enables developers to write iOS applications which interact with a user's personally controlled health record. The “go live” process to deploy an application against the production HealthVault service can be found at http://msdn.microsoft.com/en-us/healthvault/bb962148. Information about the API that the HealthVault service exposes can be in the documentation in HealthVault .NET SDK.",
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library',
  'forks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/deployments',
  'created_at': '2011-06-21T22:49:39Z',
  'updated_at': '2025-11-25T19:29:42Z',
  'pushed_at': '2017-04-28T17:05:02Z',
  'git_url': 'git://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
  'ssh_url': 'git@github.com:microsoft/HealthVault-Mobile-iOS-Library.git',
  'clone_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
  'svn_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
  'homepage': 'http://msdn.com/healthvault',
  'size': 798,
  'stargazers_count': 46,
  'watchers_count': 46,
  'language': 'Objective-C',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 21,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 2,
  'license': None,
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 21,
  'open_issues': 2,
  'watchers': 46,
  'default_branch': 'master',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-02-07T23:28:24.121Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 3085152,
  'node_id': 'MDEwOlJlcG9zaXRvcnkzMDg1MTUy',
  'name': 'BeanSpy',
  'full_name': 'microsoft/BeanSpy',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/BeanSpy',
  'description': 'BeanSpy is an open source Java servlet technology provided by Microsoft to retrieve JMX information from Java EE application servers',
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/BeanSpy',
  'forks_url': 'https://api.github.com/repos/microsoft/BeanSpy/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/BeanSpy/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/BeanSpy/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/BeanSpy/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/BeanSpy/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/BeanSpy/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/BeanSpy/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/BeanSpy/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/BeanSpy/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/BeanSpy/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/BeanSpy/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/BeanSpy/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/BeanSpy/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/BeanSpy/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/BeanSpy/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/BeanSpy/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/BeanSpy/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/BeanSpy/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/BeanSpy/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/BeanSpy/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/BeanSpy/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/BeanSpy/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/BeanSpy/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/BeanSpy/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/BeanSpy/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/BeanSpy/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/BeanSpy/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/BeanSpy/deployments',
  'created_at': '2012-01-02T02:03:37Z',
  'updated_at': '2025-08-13T11:09:28Z',
  'pushed_at': '2022-09-22T15:27:15Z',
  'git_url': 'git://github.com/microsoft/BeanSpy.git',
  'ssh_url': 'git@github.com:microsoft/BeanSpy.git',
  'clone_url': 'https://github.com/microsoft/BeanSpy.git',
  'svn_url': 'https://github.com/microsoft/BeanSpy',
  'homepage': '',
  'size': 226,
  'stargazers_count': 25,
  'watchers_count': 25,
  'language': 'Java',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 18,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 5,
  'license': {'key': 'other',
   'name': 'Other',
   'spdx_id': 'NOASSERTION',
   'url': None,
   'node_id': 'MDc6TGljZW5zZTA='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 18,
  'open_issues': 5,
  'watchers': 25,
  'default_branch': 'master',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-04-09T04:30:50.639Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 4047810,
  'node_id': 'MDEwOlJlcG9zaXRvcnk0MDQ3ODEw',
  'name': 'healthvault-ios-sdk',
  'full_name': 'microsoft/healthvault-ios-sdk',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/healthvault-ios-sdk',
  'description': 'This library is used for the HealthVault for iPhone app. Ongoing updates & bug fixes',
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk',
  'forks_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/deployments',
  'created_at': '2012-04-17T01:33:37Z',
  'updated_at': '2026-06-12T09:43:00Z',
  'pushed_at': '2017-10-10T17:03:00Z',
  'git_url': 'git://github.com/microsoft/healthvault-ios-sdk.git',
  'ssh_url': 'git@github.com:microsoft/healthvault-ios-sdk.git',
  'clone_url': 'https://github.com/microsoft/healthvault-ios-sdk.git',
  'svn_url': 'https://github.com/microsoft/healthvault-ios-sdk',
  'homepage': '',
  'size': 10007,
  'stargazers_count': 27,
  'watchers_count': 27,
  'language': 'C',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 15,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 2,
  'license': {'key': 'other',
   'name': 'Other',
   'spdx_id': 'NOASSERTION',
   'url': None,
   'node_id': 'MDc6TGljZW5zZTA='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 15,
  'open_issues': 2,
  'watchers': 27,
  'default_branch': 'microsoft/develop',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-02-07T23:28:25.167Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 5590199,
  'node_id': 'MDEwOlJlcG9zaXRvcnk1NTkwMTk5',
  'name': 'WindowsAzureToolkitForEclipseWithJava',
  'full_name': 'microsoft/WindowsAzureToolkitForEclipseWithJava',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,

In [ ]:
len(response.json())

30

In [ ]:
response.json()[0]

{'id': 1932083,
 'node_id': 'MDEwOlJlcG9zaXRvcnkxOTMyMDgz',
 'name': 'HealthVault-Mobile-iOS-Library',
 'full_name': 'microsoft/HealthVault-Mobile-iOS-Library',
 'private': False,
 'owner': {'login': 'microsoft',
  'id': 6154722,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/microsoft',
  'html_url': 'https://github.com/microsoft',
  'followers_url': 'https://api.github.com/users/microsoft/followers',
  'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
  'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
  'organizations_url': 'https://api.github.com/users/microsoft/orgs',
  'repos_url': 'https://api.github.com/users/microsoft/repos',
  'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/microsoft/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
 'description': "The HealthVault team has recently added the capability to write applications that will run on Mobile Devices and connect directly to the HealthVault Service. HealthVault iOS library enables developers to write iOS applications which interact with a user's personally controlled health record. The “go live” process to deploy an application against the production HealthVault service can be found at http://msdn.microsoft.com/en-us/healthvault/bb962148. Information about the API that the HealthVault service exposes can be in the documentation in HealthVault .NET SDK.",
 'fork': False,
 'url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library',
 'forks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/forks',
 'keys_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/teams',
 'hooks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/hooks',
 'issue_events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/events',
 'assignees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/tags',
 'blobs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/languages',
 'stargazers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/stargazers',
 'contributors_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contributors',
 'subscribers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscribers',
 'subscription_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscription',
 'commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/merges',
 'archive_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/downloads',
 'issues_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/labels{/name}',
 'releases_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/deployments',
 'created_at': '2011-06-21T22:49:39Z',
 'updated_at': '2025-11-25T19:29:42Z',
 'pushed_at': '2017-04-28T17:05:02Z',
 'git_url': 'git://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
 'ssh_url': 'git@github.com:microsoft/HealthVault-Mobile-iOS-Library.git',
 'clone_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
 'svn_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
 'homepage': 'http://msdn.com/healthvault',
 'size': 798,
 'stargazers_count': 46,
 'watchers_count': 46,
 'language': 'Objective-C',
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': False,
 'forks_count': 21,
 'mirror_url': None,
 'archived': True,
 'disabled': False,
 'open_issues_count': 2,
 'license': None,
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': [],
 'visibility': 'public',
 'forks': 21,
 'open_issues': 2,
 'watchers': 46,
 'default_branch': 'master',
 'permissions': {'admin': False,
  'maintain': False,
  'push': False,
  'triage': False,
  'pull': True},
 'custom_properties': {'activeRepoStatus': 'false',
  'durableOwnershipDisable': 'false',
  'durableOwnershipNextCheckDate': '2024-02-07T23:28:24.121Z',
  'durableOwnershipWarn': 'false',
  'global-rulesets-opt-out': 'false'}}

In [ ]:
response.json()[0]["name"]

'HealthVault-Mobile-iOS-Library'

In [ ]:
response.json()

[{'id': 1932083,
  'node_id': 'MDEwOlJlcG9zaXRvcnkxOTMyMDgz',
  'name': 'HealthVault-Mobile-iOS-Library',
  'full_name': 'microsoft/HealthVault-Mobile-iOS-Library',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
  'description': "The HealthVault team has recently added the capability to write applications that will run on Mobile Devices and connect directly to the HealthVault Service. HealthVault iOS library enables developers to write iOS applications which interact with a user's personally controlled health record. The “go live” process to deploy an application against the production HealthVault service can be found at http://msdn.microsoft.com/en-us/healthvault/bb962148. Information about the API that the HealthVault service exposes can be in the documentation in HealthVault .NET SDK.",
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library',
  'forks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/deployments',
  'created_at': '2011-06-21T22:49:39Z',
  'updated_at': '2025-11-25T19:29:42Z',
  'pushed_at': '2017-04-28T17:05:02Z',
  'git_url': 'git://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
  'ssh_url': 'git@github.com:microsoft/HealthVault-Mobile-iOS-Library.git',
  'clone_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library.git',
  'svn_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library',
  'homepage': 'http://msdn.com/healthvault',
  'size': 798,
  'stargazers_count': 46,
  'watchers_count': 46,
  'language': 'Objective-C',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 21,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 2,
  'license': None,
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 21,
  'open_issues': 2,
  'watchers': 46,
  'default_branch': 'master',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-02-07T23:28:24.121Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 3085152,
  'node_id': 'MDEwOlJlcG9zaXRvcnkzMDg1MTUy',
  'name': 'BeanSpy',
  'full_name': 'microsoft/BeanSpy',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/BeanSpy',
  'description': 'BeanSpy is an open source Java servlet technology provided by Microsoft to retrieve JMX information from Java EE application servers',
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/BeanSpy',
  'forks_url': 'https://api.github.com/repos/microsoft/BeanSpy/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/BeanSpy/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/BeanSpy/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/BeanSpy/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/BeanSpy/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/BeanSpy/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/BeanSpy/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/BeanSpy/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/BeanSpy/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/BeanSpy/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/BeanSpy/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/BeanSpy/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/BeanSpy/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/BeanSpy/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/BeanSpy/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/BeanSpy/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/BeanSpy/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/BeanSpy/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/BeanSpy/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/BeanSpy/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/BeanSpy/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/BeanSpy/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/BeanSpy/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/BeanSpy/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/BeanSpy/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/BeanSpy/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/BeanSpy/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/BeanSpy/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/BeanSpy/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/BeanSpy/deployments',
  'created_at': '2012-01-02T02:03:37Z',
  'updated_at': '2025-08-13T11:09:28Z',
  'pushed_at': '2022-09-22T15:27:15Z',
  'git_url': 'git://github.com/microsoft/BeanSpy.git',
  'ssh_url': 'git@github.com:microsoft/BeanSpy.git',
  'clone_url': 'https://github.com/microsoft/BeanSpy.git',
  'svn_url': 'https://github.com/microsoft/BeanSpy',
  'homepage': '',
  'size': 226,
  'stargazers_count': 25,
  'watchers_count': 25,
  'language': 'Java',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': False,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 18,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 5,
  'license': {'key': 'other',
   'name': 'Other',
   'spdx_id': 'NOASSERTION',
   'url': None,
   'node_id': 'MDc6TGljZW5zZTA='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 18,
  'open_issues': 5,
  'watchers': 25,
  'default_branch': 'master',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-04-09T04:30:50.639Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 4047810,
  'node_id': 'MDEwOlJlcG9zaXRvcnk0MDQ3ODEw',
  'name': 'healthvault-ios-sdk',
  'full_name': 'microsoft/healthvault-ios-sdk',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/microsoft',
   'html_url': 'https://github.com/microsoft',
   'followers_url': 'https://api.github.com/users/microsoft/followers',
   'following_url': 'https://api.github.com/users/microsoft/following{/other_user}',
   'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions',
   'organizations_url': 'https://api.github.com/users/microsoft/orgs',
   'repos_url': 'https://api.github.com/users/microsoft/repos',
   'events_url': 'https://api.github.com/users/microsoft/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/microsoft/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/microsoft/healthvault-ios-sdk',
  'description': 'This library is used for the HealthVault for iPhone app. Ongoing updates & bug fixes',
  'fork': False,
  'url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk',
  'forks_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/forks',
  'keys_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/teams',
  'hooks_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/hooks',
  'issue_events_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/events',
  'assignees_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/tags',
  'blobs_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/languages',
  'stargazers_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/stargazers',
  'contributors_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/contributors',
  'subscribers_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/subscribers',
  'subscription_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/subscription',
  'commits_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/merges',
  'archive_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/downloads',
  'issues_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/labels{/name}',
  'releases_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/microsoft/healthvault-ios-sdk/deployments',
  'created_at': '2012-04-17T01:33:37Z',
  'updated_at': '2026-06-12T09:43:00Z',
  'pushed_at': '2017-10-10T17:03:00Z',
  'git_url': 'git://github.com/microsoft/healthvault-ios-sdk.git',
  'ssh_url': 'git@github.com:microsoft/healthvault-ios-sdk.git',
  'clone_url': 'https://github.com/microsoft/healthvault-ios-sdk.git',
  'svn_url': 'https://github.com/microsoft/healthvault-ios-sdk',
  'homepage': '',
  'size': 10007,
  'stargazers_count': 27,
  'watchers_count': 27,
  'language': 'C',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 15,
  'mirror_url': None,
  'archived': True,
  'disabled': False,
  'open_issues_count': 2,
  'license': {'key': 'other',
   'name': 'Other',
   'spdx_id': 'NOASSERTION',
   'url': None,
   'node_id': 'MDc6TGljZW5zZTA='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'has_pull_requests': True,
  'pull_request_creation_policy': 'all',
  'topics': [],
  'visibility': 'public',
  'forks': 15,
  'open_issues': 2,
  'watchers': 27,
  'default_branch': 'microsoft/develop',
  'permissions': {'admin': False,
   'maintain': False,
   'push': False,
   'triage': False,
   'pull': True},
  'custom_properties': {'activeRepoStatus': 'false',
   'durableOwnershipDisable': 'false',
   'durableOwnershipNextCheckDate': '2024-02-07T23:28:25.167Z',
   'durableOwnershipWarn': 'false',
   'global-rulesets-opt-out': 'false'}},
 {'id': 5590199,
  'node_id': 'MDEwOlJlcG9zaXRvcnk1NTkwMTk5',
  'name': 'WindowsAzureToolkitForEclipseWithJava',
  'full_name': 'microsoft/WindowsAzureToolkitForEclipseWithJava',
  'private': False,
  'owner': {'login': 'microsoft',
   'id': 6154722,

In [ ]:
response.json()[0]["language"]

IndexError: list index out of range

In [ ]:
response.json()[0]["stargazers_count"]

46

In [ ]:
response.json()[0]["forks_count"]

21

In [ ]:
response.json()[0]["updated_at"]

'2025-11-25T19:29:42Z'

In [ ]:
for repo in response.json():
    print(repo["name"])

HealthVault-Mobile-iOS-Library
BeanSpy
healthvault-ios-sdk
WindowsAzureToolkitForEclipseWithJava
php-sdk-binary-tools
LIS3.5
plcrashreporter
filter-explorer
filter-effects
real-time-filter-demo
photo-inspector
camera-explorer
map-explorer
music-explorer
here-launchers
azure-puppet
weekly-planner-wp
drumkitx
diner-wp
rss-reader-wp
audio-recorder
cocos2d-x
dynamic-layout-sample
nfc-ndef-tag-reader
nfc-talk
car-trumps
drumkit-wp
bubble-level-wp
phone-info
launchapp-tag-maker

In [ ]:
data = []

for repo in response.json():
    print(repo["name"])

HealthVault-Mobile-iOS-Library
BeanSpy
healthvault-ios-sdk
WindowsAzureToolkitForEclipseWithJava
php-sdk-binary-tools
LIS3.5
plcrashreporter
filter-explorer
filter-effects
real-time-filter-demo
photo-inspector
camera-explorer
map-explorer
music-explorer
here-launchers
azure-puppet
weekly-planner-wp
drumkitx
diner-wp
rss-reader-wp
audio-recorder
cocos2d-x
dynamic-layout-sample
nfc-ndef-tag-reader
nfc-talk
car-trumps
drumkit-wp
bubble-level-wp
phone-info
launchapp-tag-maker

In [ ]:
data = []

for repo in response.json():
    data.append({
        "Company": "Microsoft",
        "Repository Name": repo["name"],
        "Description": repo["description"],
        "Language": repo["language"],
        "Stars": repo["stargazers_count"],
        "Forks": repo["forks_count"],
        "Open Issues": repo["open_issues_count"],
        "Watchers": repo["watchers_count"],
        "Created Date": repo["created_at"],
        "Updated Date": repo["updated_at"],
        "Repository URL": repo["html_url"]
    })

In [ ]:
data[0]

{'Company': 'Microsoft',
 'Repository Name': 'HealthVault-Mobile-iOS-Library',
 'Description': "The HealthVault team has recently added the capability to write applications that will run on Mobile Devices and connect directly to the HealthVault Service. HealthVault iOS library enables developers to write iOS applications which interact with a user's personally controlled health record. The “go live” process to deploy an application against the production HealthVault service can be found at http://msdn.microsoft.com/en-us/healthvault/bb962148. Information about the API that the HealthVault service exposes can be in the documentation in HealthVault .NET SDK.",
 'Language': 'Objective-C',
 'Stars': 46,
 'Forks': 21,
 'Open Issues': 2,
 'Watchers': 46,
 'Created Date': '2011-06-21T22:49:39Z',
 'Updated Date': '2025-11-25T19:29:42Z',
 'Repository URL': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library'}

In [ ]:
import pandas as pd
df = pd.DataFrame(data)

In [ ]:
df.head()

,Company,Repository Name,Description,Language,Stars,Forks,Open Issues,Watchers,Created Date,Updated Date,Repository URL
0,Microsoft,HealthVault-Mobile-iOS-Library,The HealthVault team has recently added the ca...,Objective-C,46,21,2,46,2011-06-21T22:49:39Z,2025-11-25T19:29:42Z,https://github.com/microsoft/HealthVault-Mobil...
1,Microsoft,BeanSpy,BeanSpy is an open source Java servlet technol...,Java,25,18,5,25,2012-01-02T02:03:37Z,2025-08-13T11:09:28Z,https://github.com/microsoft/BeanSpy
2,Microsoft,healthvault-ios-sdk,This library is used for the HealthVault for i...,C,27,15,2,27,2012-04-17T01:33:37Z,2026-06-12T09:43:00Z,https://github.com/microsoft/healthvault-ios-sdk
3,Microsoft,WindowsAzureToolkitForEclipseWithJava,Windows Azure Toolkit for Eclipse with Java,Java,43,38,2,43,2012-08-28T18:33:11Z,2025-03-10T12:56:21Z,https://github.com/microsoft/WindowsAzureToolk...
4,Microsoft,php-sdk-binary-tools,Tool kit for building PHP under Windows,M4,266,82,2,266,2013-05-15T09:42:29Z,2026-05-25T14:09:49Z,https://github.com/microsoft/php-sdk-binary-tools

**GitHub_API_Data_Collection**

In [ ]:
# Imported requests library to make API requests

import requests
import pandas as pd

In [ ]:
# List of GitHub organizations to analyze

import requests

companies = [
    "microsoft",
    "google",
    "oracle",
    "ibm",
    "sap",
    "salesforce",
    "snowflakedb",
    "sassoftware"
]

In [ ]:
# Created an empty list to store repository data

data = []

In [ ]:
# Loop through each company

for company in companies:
    print(company)

microsoft
google
oracle
ibm
sap
salesforce
snowflakedb
sassoftware

In [ ]:
company_count = 0

# Loop through API pages (100 repositories per page)
for page in range(1, 11):

    # Create the GitHub API URL
    url = f"https://api.github.com/orgs/{company}/repos?per_page=100&page={page}"

    # Send GET request to the GitHub API
    response = requests.get(url)

    # Convert API response to JSON format
    repos = response.json()

    # Stop if no repositories are returned
    if len(repos) == 0:
        break

    # Loop through each repository
    for repo in repos:
        company_count += 1

print(f"Collected {company_count} repositories from {company}")

Collected 143 repositories from sassoftware

In [ ]:
import requests

companies = [
    "microsoft",
    "google",
    "oracle",
    "ibm",
    "sap",
    "salesforce",
    "snowflakedb",
    "sassoftware"
]

for company in companies:

    url = f"https://api.github.com/orgs/{company}/repos?per_page=1"

    response = requests.get(url)

    if response.status_code == 200:
        print(f"{company:<15} → VALID ORGANIZATION")
    else:
        print(f"{company:<15} → NOT FOUND / NO ACCESS")

microsoft       → VALID ORGANIZATION
google          → VALID ORGANIZATION
oracle          → VALID ORGANIZATION
ibm             → VALID ORGANIZATION
sap             → VALID ORGANIZATION
salesforce      → VALID ORGANIZATION
snowflakedb     → VALID ORGANIZATION
sassoftware     → VALID ORGANIZATION

Final GitHub_API_Data_Collection

In [ ]:
# Import required libraries for API calls and data handling

import requests  # used to call GitHub API
import pandas as pd  # used to create and manage dataset
import time  # used to avoid API rate limit issues

In [ ]:
import requests

url = "https://api.github.com/orgs/microsoft/repos?per_page=1"

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.text[:300])

401
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}

In [ ]:
# GitHub token for authentication (prevents rate limit issues)

GITHUB_TOKEN = "YOUR_GITHUB_TOKEN_HERE"

# Headers for API request with authentication

headers = {
    "Authorization": f"token {GITHUB_TOKEN}"
}

In [ ]:
url = "https://api.github.com/orgs/microsoft/repos?per_page=1"

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.json()[0] if response.status_code == 200 else response.text)

200
{'id': 1932083, 'node_id': 'MDEwOlJlcG9zaXRvcnkxOTMyMDgz', 'name': 'HealthVault-Mobile-iOS-Library', 'full_name': 'microsoft/HealthVault-Mobile-iOS-Library', 'private': False, 'owner': {'login': 'microsoft', 'id': 6154722, 'node_id': 'MDEyOk9yZ2FuaXphdGlvbjYxNTQ3MjI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6154722?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/microsoft', 'html_url': 'https://github.com/microsoft', 'followers_url': 'https://api.github.com/users/microsoft/followers', 'following_url': 'https://api.github.com/users/microsoft/following{/other_user}', 'gists_url': 'https://api.github.com/users/microsoft/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/microsoft/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/microsoft/subscriptions', 'organizations_url': 'https://api.github.com/users/microsoft/orgs', 'repos_url': 'https://api.github.com/users/microsoft/repos', 'events_url': 'https://api.github.com/users/microsoft/events{/privacy}', 'received_events_url': 'https://api.github.com/users/microsoft/received_events', 'type': 'Organization', 'user_view_type': 'public', 'site_admin': False}, 'html_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library', 'description': "The HealthVault team has recently added the capability to write applications that will run on Mobile Devices and connect directly to the HealthVault Service. HealthVault iOS library enables developers to write iOS applications which interact with a user's personally controlled health record. The “go live” process to deploy an application against the production HealthVault service can be found at http://msdn.microsoft.com/en-us/healthvault/bb962148. Information about the API that the HealthVault service exposes can be in the documentation in HealthVault .NET SDK.", 'fork': False, 'url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library', 'forks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/forks', 'keys_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/keys{/key_id}', 'collaborators_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/collaborators{/collaborator}', 'teams_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/teams', 'hooks_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/hooks', 'issue_events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/events{/number}', 'events_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/events', 'assignees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/assignees{/user}', 'branches_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/branches{/branch}', 'tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/tags', 'blobs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/blobs{/sha}', 'git_tags_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/tags{/sha}', 'git_refs_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/refs{/sha}', 'trees_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/trees{/sha}', 'statuses_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/statuses/{sha}', 'languages_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/languages', 'stargazers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/stargazers', 'contributors_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contributors', 'subscribers_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscribers', 'subscription_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/subscription', 'commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/commits{/sha}', 'git_commits_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/git/commits{/sha}', 'comments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/comments{/number}', 'issue_comment_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues/comments{/number}', 'contents_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/contents/{+path}', 'compare_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/compare/{base}...{head}', 'merges_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/merges', 'archive_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/{archive_format}{/ref}', 'downloads_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/downloads', 'issues_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/issues{/number}', 'pulls_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/pulls{/number}', 'milestones_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/milestones{/number}', 'notifications_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/notifications{?since,all,participating}', 'labels_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/labels{/name}', 'releases_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/releases{/id}', 'deployments_url': 'https://api.github.com/repos/microsoft/HealthVault-Mobile-iOS-Library/deployments', 'created_at': '2011-06-21T22:49:39Z', 'updated_at': '2025-11-25T19:29:42Z', 'pushed_at': '2017-04-28T17:05:02Z', 'git_url': 'git://github.com/microsoft/HealthVault-Mobile-iOS-Library.git', 'ssh_url': 'git@github.com:microsoft/HealthVault-Mobile-iOS-Library.git', 'clone_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library.git', 'svn_url': 'https://github.com/microsoft/HealthVault-Mobile-iOS-Library', 'homepage': 'http://msdn.com/healthvault', 'size': 798, 'stargazers_count': 46, 'watchers_count': 46, 'language': 'Objective-C', 'has_issues': True, 'has_projects': True, 'has_downloads': True, 'has_wiki': False, 'has_pages': False, 'has_discussions': False, 'forks_count': 21, 'mirror_url': None, 'archived': True, 'disabled': False, 'open_issues_count': 2, 'license': None, 'allow_forking': True, 'is_template': False, 'web_commit_signoff_required': False, 'has_pull_requests': True, 'pull_request_creation_policy': 'all', 'topics': [], 'visibility': 'public', 'forks': 21, 'open_issues': 2, 'watchers': 46, 'default_branch': 'master', 'permissions': {'admin': False, 'maintain': False, 'push': False, 'triage': False, 'pull': True}, 'custom_properties': {'activeRepoStatus': 'false', 'durableOwnershipDisable': 'false', 'durableOwnershipNextCheckDate': '2024-02-07T23:28:24.121Z', 'durableOwnershipWarn': 'false', 'global-rulesets-opt-out': 'false'}}

In [ ]:
# List of data analytics related companies (GitHub organizations)

companies = [
    "microsoft",      # Microsoft - Power BI, Azure
    "google",         # Google - BigQuery, Looker
    "oracle",         # Oracle - Database & analytics
    "ibm",            # IBM - Cognos, analytics tools
    "sap",            # SAP - Business analytics tools
    "salesforce",     # Salesforce - CRM analytics
    "snowflakedb",    # Snowflake - Cloud data warehouse
    "sassoftware"     # SAS - Statistical analytics
]

In [ ]:
# Empty list to store all repository data

data = []

In [ ]:
for company in companies:

    print(f"\nCollecting data from {company}...")

    company_count = 0
    page = 1

    while True:

        url = f"https://api.github.com/orgs/{company}/repos"

        params = {
            "per_page": 100,
            "page": page
        }

        response = requests.get(url, headers=headers, params=params)

        # Check API response
        if response.status_code != 200:
            print(f"Error {response.status_code} for {company}")
            break

        repos = response.json()

        # Stop if no more repositories
        if not repos:
            break

        for repo in repos:

            data.append({
                "Company": company,
                "Repository Name": repo["name"],
                "Description": repo["description"],
                "Language": repo["language"],
                "Stars": repo["stargazers_count"],
                "Forks": repo["forks_count"],
                "Open Issues": repo["open_issues_count"],
                "Watchers": repo["watchers_count"],
                "Created Date": repo["created_at"],
                "Updated Date": repo["updated_at"],
                "Repository URL": repo["html_url"]
            })

            company_count += 1

        print(f"Page {page} completed | Total: {company_count}")

        page += 1

    print(f"Collected {company_count} repositories from {company}")

Collecting data from microsoft...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 400
Page 5 completed | Total: 500
Page 6 completed | Total: 600
Page 7 completed | Total: 700
Page 8 completed | Total: 800
Page 9 completed | Total: 900
Page 10 completed | Total: 1000
Page 11 completed | Total: 1100
Page 12 completed | Total: 1200
Page 13 completed | Total: 1300
Page 14 completed | Total: 1400
Page 15 completed | Total: 1500
Page 16 completed | Total: 1600
Page 17 completed | Total: 1700
Page 18 completed | Total: 1800
Page 19 completed | Total: 1900
Page 20 completed | Total: 2000
Page 21 completed | Total: 2100
Page 22 completed | Total: 2200
Page 23 completed | Total: 2300
Page 24 completed | Total: 2400
Page 25 completed | Total: 2500
Page 26 completed | Total: 2600
Page 27 completed | Total: 2700
Page 28 completed | Total: 2800
Page 29 completed | Total: 2900
Page 30 completed | Total: 3000
Page 31 completed | Total: 3100
Page 32 completed | Total: 3200
Page 33 completed | Total: 3300
Page 34 completed | Total: 3400
Page 35 completed | Total: 3500
Page 36 completed | Total: 3600
Page 37 completed | Total: 3700
Page 38 completed | Total: 3800
Page 39 completed | Total: 3900
Page 40 completed | Total: 4000
Page 41 completed | Total: 4100
Page 42 completed | Total: 4200
Page 43 completed | Total: 4300
Page 44 completed | Total: 4400
Page 45 completed | Total: 4500
Page 46 completed | Total: 4600
Page 47 completed | Total: 4700
Page 48 completed | Total: 4800
Page 49 completed | Total: 4900
Page 50 completed | Total: 5000
Page 51 completed | Total: 5100
Page 52 completed | Total: 5200
Page 53 completed | Total: 5300
Page 54 completed | Total: 5400
Page 55 completed | Total: 5500
Page 56 completed | Total: 5600
Page 57 completed | Total: 5700
Page 58 completed | Total: 5800
Page 59 completed | Total: 5900
Page 60 completed | Total: 6000
Page 61 completed | Total: 6100
Page 62 completed | Total: 6200
Page 63 completed | Total: 6300
Page 64 completed | Total: 6400
Page 65 completed | Total: 6500
Page 66 completed | Total: 6600
Page 67 completed | Total: 6700
Page 68 completed | Total: 6800
Page 69 completed | Total: 6900
Page 70 completed | Total: 7000
Page 71 completed | Total: 7100
Page 72 completed | Total: 7200
Page 73 completed | Total: 7300
Page 74 completed | Total: 7400
Page 75 completed | Total: 7500
Page 76 completed | Total: 7600
Page 77 completed | Total: 7700
Page 78 completed | Total: 7800
Page 79 completed | Total: 7900
Page 80 completed | Total: 8000
Page 81 completed | Total: 8100
Page 82 completed | Total: 8163
Collected 8163 repositories from microsoft

Collecting data from google...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 400
Page 5 completed | Total: 500
Page 6 completed | Total: 600
Page 7 completed | Total: 700
Page 8 completed | Total: 800
Page 9 completed | Total: 900
Page 10 completed | Total: 1000
Page 11 completed | Total: 1100
Page 12 completed | Total: 1200
Page 13 completed | Total: 1300
Page 14 completed | Total: 1400
Page 15 completed | Total: 1500
Page 16 completed | Total: 1600
Page 17 completed | Total: 1700
Page 18 completed | Total: 1800
Page 19 completed | Total: 1900
Page 20 completed | Total: 2000
Page 21 completed | Total: 2100
Page 22 completed | Total: 2200
Page 23 completed | Total: 2300
Page 24 completed | Total: 2400
Page 25 completed | Total: 2500
Page 26 completed | Total: 2600
Page 27 completed | Total: 2700
Page 28 completed | Total: 2800
Page 29 completed | Total: 2881
Collected 2881 repositories from google

Collecting data from oracle...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 313
Collected 313 repositories from oracle

Collecting data from ibm...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 400
Page 5 completed | Total: 500
Page 6 completed | Total: 600
Page 7 completed | Total: 700
Page 8 completed | Total: 800
Page 9 completed | Total: 900
Page 10 completed | Total: 1000
Page 11 completed | Total: 1100
Page 12 completed | Total: 1200
Page 13 completed | Total: 1300
Page 14 completed | Total: 1400
Page 15 completed | Total: 1500
Page 16 completed | Total: 1600
Page 17 completed | Total: 1700
Page 18 completed | Total: 1800
Page 19 completed | Total: 1900
Page 20 completed | Total: 2000
Page 21 completed | Total: 2100
Page 22 completed | Total: 2200
Page 23 completed | Total: 2300
Page 24 completed | Total: 2400
Page 25 completed | Total: 2500
Page 26 completed | Total: 2600
Page 27 completed | Total: 2700
Page 28 completed | Total: 2800
Page 29 completed | Total: 2900
Page 30 completed | Total: 3000
Page 31 completed | Total: 3100
Page 32 completed | Total: 3200
Page 33 completed | Total: 3300
Page 34 completed | Total: 3400
Page 35 completed | Total: 3500
Page 36 completed | Total: 3600
Page 37 completed | Total: 3700
Page 38 completed | Total: 3800
Page 39 completed | Total: 3900
Page 40 completed | Total: 3912
Collected 3912 repositories from ibm

Collecting data from sap...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 309
Collected 309 repositories from sap

Collecting data from salesforce...
Page 1 completed | Total: 100
Page 2 completed | Total: 200
Page 3 completed | Total: 300
Page 4 completed | Total: 400
Page 5 completed | Total: 417
Collected 417 repositories from salesforce

Collecting data from snowflakedb...
Page 1 completed | Total: 63
Collected 63 repositories from snowflakedb

Collecting data from sassoftware...
Page 1 completed | Total: 100
Page 2 completed | Total: 143
Collected 143 repositories from sassoftware

In [ ]:
import pandas as pd

df = pd.DataFrame(data)

print("Shape:", df.shape)
df.head()

Shape: (16201, 11)

,Company,Repository Name,Description,Language,Stars,Forks,Open Issues,Watchers,Created Date,Updated Date,Repository URL
0,microsoft,HealthVault-Mobile-iOS-Library,The HealthVault team has recently added the ca...,Objective-C,46,21,2,46,2011-06-21T22:49:39Z,2025-11-25T19:29:42Z,https://github.com/microsoft/HealthVault-Mobil...
1,microsoft,BeanSpy,BeanSpy is an open source Java servlet technol...,Java,25,18,5,25,2012-01-02T02:03:37Z,2025-08-13T11:09:28Z,https://github.com/microsoft/BeanSpy
2,microsoft,healthvault-ios-sdk,This library is used for the HealthVault for i...,C,27,15,2,27,2012-04-17T01:33:37Z,2026-06-12T09:43:00Z,https://github.com/microsoft/healthvault-ios-sdk
3,microsoft,WindowsAzureToolkitForEclipseWithJava,Windows Azure Toolkit for Eclipse with Java,Java,43,38,2,43,2012-08-28T18:33:11Z,2025-03-10T12:56:21Z,https://github.com/microsoft/WindowsAzureToolk...
4,microsoft,php-sdk-binary-tools,Tool kit for building PHP under Windows,M4,266,82,2,266,2013-05-15T09:42:29Z,2026-05-25T14:09:49Z,https://github.com/microsoft/php-sdk-binary-tools

In [ ]:
print("DataFrame shape:", df.shape)
print("Data list length:", len(data))

DataFrame shape: (4012, 11)
Data list length: 4012

In [ ]:
df.to_excel("test_check.xlsx", index=False)

print("Export done")

Export done

In [ ]:
df.to_csv("github_analysis.csv", index=False)
df.to_excel("github_analysis.xlsx", index=False)